### ISSUE TITLE
[Question]: Regarding the scratch bytes required for Base2K normalization

### ISSUE THREAD

**Issue by Pro7ech** [tfhe/spqlios-arithmetic#28]
The library offers two ways to normalize a Base2K vector:
- [znx_normalize](https://github.com/tfhe/spqlios-arithmetic/blob/2ce219a9750882a9d7e176df3193c832a75ebf88/spqlios/coeffs/coeffs_arithmetic.h#L70): which must be called iteratively on each limb
- [vec_znx_normalize_base2k](https://github.com/tfhe/spqlios-arithmetic/blob/2ce219a9750882a9d7e176df3193c832a75ebf88/spqlios/arithmetic/vec_znx_arithmetic.h#L102): which manages the reduction for all limbs automatically

Both require a buffer to store the carry, but `znx_normalize` takes an array of `int64`, expected to be of size `N`, while `vec_znx_normalize_base2k` requires an array of `byte`, which expected to be of size [`N*sizeof(int64_t)`](https://github.com/tfhe/spqlios-arithmetic/blob/2ce219a9750882a9d7e176df3193c832a75ebf88/spqlios/arithmetic/vec_znx.c#L250), so the same size. 

Everything seems to indicate that the type of these buffers could be uniformized. Is there a reason for the difference between the argument types between those two functions?

Additionally, [vec_znx_normalize_base2k_tmp_bytes_ref](https://github.com/tfhe/spqlios-arithmetic/blob/2ce219a9750882a9d7e176df3193c832a75ebf88/spqlios/arithmetic/vec_znx.c#L250) takes two arguments, which if I understand are supposed to be the number of limbs of the input and output vectors, but these have no effect on its output since it always returns `N*size_of(int64_t)`. 

## action-items

- [x] remove the unnecessary arguments from `vec_znx_normalize_base2k_tmp_bytes_ref`
- [x] remove the unnecessary arguments from `vec_znx_big_normalize_base2k_tmp_bytes`
- [x] remove the unnecessary arguments from `vec_znx_big_range_normalize_base2k_tmp_bytes`
- [x] update the documentation if needed.

**Comment by ngama75** [comment]
good catch, yes agreed, we should remove the vector sizes from `vec_znx_normalize_base2k_tmp_bytes`, it can take only the module as argument.

IMO, normalization is also almost never time-critical, so we could even maybe expose a variant without tmp, that do non-sequential memory accesses.
